repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    - id: black
  
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
    - id: ruff
      args: [--fix]
  